[cosmic-ray]
module-path = "/home/theoportlock/tis"
python-version = ""
timeout = 10
excluded-modules = []
test-command = "pytest"

[cosmic-ray.execution-engine]
name = "local"

[cosmic-ray.cloning]
method = "copy"
commands = []
